### ISSUE TITLE
problem build release

### ISSUE THREAD

**Issue by prozaklob** [jadennn/flutter_ijk#22]
hello!

```
dependencies:
  flutter:
    sdk: flutter
  flutter_ijk:
    git:
      url: https://github.com/jadennn/flutter_ijk

```

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_ijk'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 731ms


The plugin flutter_ijk could not be built due to the issue above.
```
